version: "3"
services:
  grafana:
    image: grafana/grafana:8.2.3
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-config:/etc/grafana/provisioning
      - ./grafana-dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SERVER_ENABLE_GZIP=true
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=data/temps.json
    networks:
      - evohome
    restart: unless-stopped
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    networks:
      - evohome
    restart: unless-stopped
    volumes:
      - ./influxdb:/var/lib/influxdb
  evohome:
    image: evohome:latest
    depends_on:
      - influxdb
    links:
      - influxdb
    networks:
      - evohome
    restart: unless-stopped
    env_file:
      - ./local.env
    environment:
      - OW=true
        #      - HEALTHCHECKS-IO=https://hc-ping.com/XXXX-YYYY-ZZZZ
networks:
  evohome:
volumes:
  influxdb:
  grafana-storage:
