version: "3"
services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-storage:/var/lib/grafana
      - ./grafana-config:/etc/grafana/provisioning
      - ./grafana-dashboards:/var/lib/grafana/dashboards
    networks:
      - evohome_network
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    networks:
      - evohome_network
    volumes:
      - ./influxdb:/var/lib/influxdb
  evohome:
    image: evohome:latest
    links:
      - influxdb
    networks:
      - evohome_network
    environment:
      - EH-USERNAME=wibble@email.address
      - EH-PASSWORD=5up3r53cr3tp4ssw0rd1
      - OW=true
      - OW-API-KEY=123123123123
      - OW-CITY=London,uk
networks:
  evohome_network:
volumes:
  influxdb:
  grafana-storage: